
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: 
      context: ./serveur
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm install && npm start"

  apiDev:
    image: node:lts
    container_name: apiDev
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./serveur:/usr/src/app
    command: sh -c "cd /usr/src/app && npm install && npm run watch"

volumes:
  db_data: